version: '3.3'
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file: .env
    volumes:
      - './${POSTGRES_DB}:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT}:5432'
  redis:
    container_name: rd
    image: redis:alpine
    volumes:
      - /etc/redis/:/data
    ports:
      - 6379:6379
