POST {{base_url}}/api/task
Content-Type: application/json

{
  "task": "task"
}
> {%
client.test("Запуск задачи celery", function() {
  client.assert(
      (response.body['success'] === "ok") ||
      (response.body['msg'] === "task"),
  'api post request not available!'
   );
});
%}

###
GET {{base_url}}/api/
Accept: application/json

